background/urls.py
from unicodedata import name
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('customers/<str:pk>', views.customerinfo, name="customerinfo"),
]

c3prototype/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.views.generic.base import TemplateView
from background import views as BGv
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path("register/", BGv.register, name="register"), 
    path('', include('background.urls')),
    path('', include("django.contrib.auth.urls")),
    path('reporting/', include('reporting.urls', namespace='reporting')),
    path('inventory/orders/', include('inventory.urls')),
    path('inspections/', include('inspections.urls')),    
    path('__debug__/', include('debug_toolbar.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inspections/urls.py
from django.urls import path
from . import views

app_name = 'inspections'

urlpatterns = [
    path('all', views.inspections_all, name="all"),
    path("<int:id>/", views.inspection_detail_view, name='detail'),
    path("create/", views.inspection_create_view, name='create'),
    path("<int:id>/edit/", views.inspection_update_view, name='update'),
]

inventory/urls.py
from django.urls import path

from .views import (
    order_form_list_view,
    order_form_detail_view,
    order_form_create_view,
    order_form_update_view,
    order_form_start_view
)

app_name='inventory'

urlpatterns = [
    path("", order_form_list_view, name='list'),
    path("create/", order_form_create_view, name='create'),
    path("<int:id>/edit/", order_form_update_view, name='update'),
    path("<int:id>/", order_form_detail_view, name='detail'),
    path("<int:id>/start/", order_form_start_view, name='start'),
]

reporting/urls.py
from django.urls import path
from . import views
##from c3prototype import reporting

app_name = 'reporting'

urlpatterns = [

    path('', views.index, name='index'),
    path('inventory', views.inventory, name='inventory'),
    path('inspection', views.insFilterView, name='inspection')
]

background/models.py
from django.db import models

# Create your models here.
class Customer(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    email = models.EmailField()
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    province = models.CharField(max_length=200)
    country = models.CharField(max_length=200)
    phone = models.CharField(max_length=200, blank=True)
    def __str__(self):
        return self.first_name + " " + self.last_name

class Dealership(models.Model):
    dealership = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    province = models.CharField(max_length=200)
    country = models.CharField(max_length=200)
    def __str__(self):
        return self.dealership

class Employee(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    email = models.EmailField()
    phone = models.CharField(max_length=200, blank=True)
    type = models.CharField(max_length=200)
    def __str__(self):
        return self.first_name + " " + self.last_name

class Product(models.Model):
    name = models.CharField(max_length=200)
    category = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image = models.ImageField(upload_to = 'images/product')
    def __str__(self):
        return self.name + ",  @$" + str(self.price)

inspections/models.py
from bdb import effective
from django.db import models
from django.urls import reverse
from django.core.exceptions import ValidationError

#based on https://gist.github.com/krisneuharth/2176789
def validate_vin(value):
    POSITIONAL_WEIGHTS = [8,7,6,5,4,3,2,10,0,9,8,7,6,5,4,3,2]
    ILLEGAL_ALL = ['I', 'O', 'Q']
    ILLEGAL_TENTH = ['U','Z','0']
    LETTER_KEY = dict(
        A=1,B=2,C=3,D=4,E=5,F=6,G=7,H=8,
        J=1,K=2,L=3,M=4,N=5,    P=7,    R=9,
            S=2,T=3,U=4,V=5,W=6,X=7,Y=8,Z=9,
    )

    if len(value) == 17:
        vin = value.upper()

        for char in ILLEGAL_ALL:
            if char in vin:
                raise ValidationError('Field cannot contain "I", "O", or "Q".')

        if vin[9] in ILLEGAL_TENTH:
            raise ValidationError('Field cannot contain "U", "Z", or "0" in position 10.')

        check_digit = vin[8]

        pos=sum=0
        for char in vin:
            value = int(LETTER_KEY[char]) if char in LETTER_KEY else int(char)
            weight = POSITIONAL_WEIGHTS[pos]
            sum += (value * weight)
            pos += 1

        calc_check_digit = int(sum) % 11

        if calc_check_digit == 10:
            calc_check_digit = 'X'

        if str(check_digit) != str(calc_check_digit):
            raise ValidationError('Invalid VIN.')
    else:
        raise ValidationError('Field must be 17 characters.')

# Create your models here.
class warrantyManager(models.Manager):
    def get_queryset(self):
        return super(warrantyManager, self).get_queryset().select_related()

class warranty(models.Model):
    dealershipID = models.ForeignKey('background.Dealership', on_delete=models.PROTECT)
    customerID = models.ForeignKey('background.Customer', on_delete=models.PROTECT)
    products = models.TextField(max_length=200)
    productBundle = models.BooleanField()
    extendedW = models.BooleanField()
    effectiveDate = models.DateTimeField()
    expiryDate = models.DateTimeField()
    timestamp = models.DateTimeField(auto_now=True)
    objects = warrantyManager()
    def __str__(self):
        return "W"+ str(self.id) + "| " + str(self.customerID)

class claimManager(models.Manager):
    def get_queryset(self):
        return super(claimManager, self).get_queryset().select_related()

class claim(models.Model):
    warrantyID = models.ForeignKey(warranty, on_delete=models.PROTECT)
    description = models.TextField(max_length=3000)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    province = models.CharField(max_length=200)
    country = models.CharField(max_length=200)
    STATUS_CHOICES = [
        ('Pn', 'Pending'),
        ('Ap', 'Approved'),
        ('Sb', 'Submitted'),
        ('Pd', 'Paid')
    ]
    status = models.CharField(
        max_length=2,
        choices=STATUS_CHOICES,
        default='Pn',
    )
    date = models.DateTimeField(auto_now_add=True)
    timestamp = models.DateTimeField(auto_now=True)
    objects = claimManager()

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return "C"+ str(self.id) + "| " + str(self.warrantyID)

class inspectionManager(models.Manager):
    def get_queryset(self):
        return super(inspectionManager, self).get_queryset().select_related()

class inspection(models.Model):
    claimID = models.ForeignKey(claim, on_delete=models.PROTECT)
    vin = models.CharField(
        max_length=200,
        validators =[validate_vin])
    make = models.CharField(max_length=200)
    model = models.CharField(max_length=200)
    year = models.DecimalField(max_digits=4, decimal_places=0)
    colour = models.CharField(max_length=200)
    STATUS_CHOICES = [
        ('Sc', 'Scheduled'),
        ('Cm', 'Completed'),
        ('Ex', 'Expired')
    ]
    status = models.CharField(
        max_length=2,
        choices=STATUS_CHOICES,
        default='Sc',
    )
    scheduledDate = models.DateField()
    scheduledTime = models.TimeField()
    objects = inspectionManager()
    def list(self):
        return self.id

    def __str__(self):
        return  "I"+ str(self.id) + "| " + str(self.year) + " " + self.colour + " " +  self.make + " " +  self.model

    def get_absolute_url(self):
        return reverse("inspections:detail", kwargs={"id": self.id})

    def get_edit_url(self):
        return reverse("inspections:update", kwargs={"id": self.id})

background/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

background/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from .forms import RegisterForm
from django.db.models import Count

from django.db.models.functions import Coalesce

from .models import *
from inspections.models import claim, inspection
from .decorators import *

def home(request):
    if not request.user.is_authenticated:
        return render(request = request,
                    template_name='background/home.html',
                    context = {"products":Product.objects.all})
    else:
        if request.user.is_staff:
            customers = Customer.objects.all().annotate(inspection_count=Coalesce(Count('warranty__claim__inspection'),0))
            header = "Customer List"
            table_css_id = "table_db"
        else:
            customers = Customer.objects.filter(email = request.user.email).annotate(inspection_count=Coalesce(Count('warranty__claim__inspection'),0)) #Add inspection count to cust view
            customer = customers.first().first_name
            header = "Welcome " + customer + "!"
            table_css_id = "tableOne"
        context = {
            "customers": customers,
            "header": header,
            "table_css_id": table_css_id,
        }
        return render(request, 'background/customers.html', context)

def customerinfo(request, pk):
    customer = Customer.objects.get(id=pk)
    warranties = customer.warranty_set.all()
    claims = [claim
                for warranty in warranties
                for claim in warranty.claim_set.all()]
    inspections = [inspection
                    for claim in claims
                    for inspection in claim.inspection_set.all()]
    context = {'customer':customer, 'warranties':warranties, 'claims':claims, 'inspections':inspections}
    return render(request, 'background/customerinfo.html', context)

def register(response):
    if response.method == "POST":
        form = RegisterForm(response.POST)
        if form.is_valid():
            form.save()

            return redirect("/")
    else:
        form = RegisterForm()

    return render(response, "background/register.html", {"form":form})

background/templates/background/base.html
<!DOCTYPE html>

{% load static %}
<html>

<head>
  <meta charset="utf-8">
  <title>{% block title %}C3 Saviour System{% endblock %}</title>
  <!-- Bootstrap -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>

  <!-- HTMX -->
  <script src="https://unpkg.com/htmx.org@1.7.0"></script>
  <!-- jQuery -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

  <!-- FontAwesome -->
  <script src="https://kit.fontawesome.com/50028f906b.js" crossorigin="anonymous"></script>

  <!-- Datatables -->
  <link rel="stylesheet" type="text/css"
    href="https://cdn.datatables.net/v/bs5/jszip-2.5.0/dt-1.11.5/b-2.2.2/b-colvis-2.2.2/b-html5-2.2.2/b-print-2.2.2/cr-1.5.5/datatables.min.css" />

  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
  <script type="text/javascript"
    src="https://cdn.datatables.net/v/bs5/jszip-2.5.0/dt-1.11.5/b-2.2.2/b-colvis-2.2.2/b-html5-2.2.2/b-print-2.2.2/cr-1.5.5/datatables.min.js"></script>
</head>

<body>
  {% include 'background/message.html' %}
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand mx-2" href="{% url 'home'%}">C3 Saviour System</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse mx-2" id="mynavbar">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link disabled" href="{% url 'home'%}">Warranties</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="{% url 'home'%}">Claims</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
              aria-expanded="false">
              Inspections
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'inspections:all' %}">Inspections Home</a>
              <a class="dropdown-item" href="{% url 'inspections:create' %}">New Inspection</a>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="{% url 'home'%}">Sales</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
              aria-expanded="false">
              Inventory
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'inventory:list' %}">Orders Home</a>
              <a class="dropdown-item" href="{% url 'inventory:create' %}">New Order</a>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
              aria-expanded="false">
              Reporting
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'reporting:index' %}">Reporting Home</a>
              <a class="dropdown-item disabled" href="#">Claims</a>
              <a class="dropdown-item" href="{% url 'reporting:inspection' %}">Inspections</a>
              <a class="dropdown-item disabled" href="#">Sales</a>
              <a class="dropdown-item" href="{% url 'reporting:inventory' %}">Inventory</a>
            </ul>
          </li>
        </ul>
        <div class="d-flex">
          {% if user.is_authenticated %}
          <div class="nav-link disabled">Hello, {{ user.username }}.</div>
          <a class="btn btn-primary" type="button" href="{% url 'logout' %}">Logout</a>
          {% else %}
          <a class="btn btn-success mx-2" type="button" href="{% url 'register' %}">Register</a>
          <a class="btn btn-primary mx-2" type="button" href="{% url 'login' %}">Login</a>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>


  <main class="container-xxl">
    <br>
    {% block content %}
    {% endblock %}
    {% block js %}
    {% endblock js %}
  </main>
</body>
<!-- Toasts -->
{% if messages %}
<script>
  {% for message in messages %}
  $(document).ready(function () {
    $('.toast').toast('show');
  });
  {% endfor %}
</script>
{% endif %}

</html>

background/templates/background/customerinfo.html
{% extends 'background/base.html' %}

{% block title %}{{customer.first_name}} {{customer.last_name}}{% endblock %}

{% block content %}

<body>
    <div class="row">
        <div class="col-md-3 ">
            <div class="card mb-4">
                <button type="button" class="btn btn-secondary btn-lg btn-block" onclick="history.back()">Go Back</button>
            </div>
            <div class="card">
                <div class="card card-body text-white bg-primary">
                    <h5 class="card-title">{{customer.first_name}} {{customer.last_name}}</h5>
                    <h6 class="card-subtitle mb-2">{{customer.email}}</h6>
                    <p class="card-text">{{customer.address}}<br>
                        {{customer.city}}, {{customer.province}}, {{customer.country}}
                    </p>
                    <p class="card-text">{{customer.phone}}</p>
                </div>
            </div>
        </div>
        <div class="col-md-9 d-flex align-items-stretch">
            <div class="card card-body card border-primary">
                <h5 class="card-title">Warranties</h5>
                <table class="table">
                    <thead>
                    <tr>
                        <th>Dealership</th>
                        <th>Products Active</th>
                        <th>Expiry Date</th>
                        <th>ID</th>
                    </tr>
                </thead>
                <tbody>
                    {% for war in warranties %}
                        <tr>
                            <td>{{war.dealershipID}}</td>
                            <td>{{war.products}}</td>
                            <td>{{war.expiryDate|date:"M d, Y" }}</td>
                            <td>{{war.id}}</td>
                        </tr>
                    {% endfor%}
                </tbody>
                </table>
            </div>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-xl-5 d-flex mb-4 align-items-stretch">
            <div class="card card-body card border-primary">
                <h5 class="card-title">Claims</h5>
                <table class="table">
                    <tr>
                        <th>Warranty ID</th>
                        <th>Description</th>
                        <th>Date</th>
                        <th>Status</th>
                        <th>ID</th>
                    </tr>
                    {% for claim in claims %}
                        <tr>
                            <td>{{claim.warrantyID.id}}</td>
                            <td>{{claim.description}}</td>
                            <td>{{claim.date|date:"M d, Y" }}</td>
                            <td>{{claim.get_status_display}}</td>
                            <td>{{claim.id}}</td>
                        </tr>
                    {% endfor%}
                </table>
            </div>
        </div>
        <div class="col-xl-7 d-flex align-items-stretch">
            <div class="card card-body card border-primary">
                <h5 class="card-title">Inspections</h5>
                <table class="table">
                    <tr>
                        <th>Claim ID</th>
                        <th>VIN</th>
                        <th>Make</th>
                        <th>Model</th>
                        <th>Year</th>
                        <th>Colour</th>
                        <th>Status</th>
                        <th>Date</th>
                        <th>ID</th>
                    </tr>
                    {% for ins in inspections %}
                        <tr>
                            <td>{{ins.claimID.id}}</td>
                            <td>{{ins.vin|make_list|slice:":8"|join:""}}<wbr>{{ins.vin|make_list|slice:"8:"|join:""}}</td>
                            <td>{{ins.make}}</td>
                            <td>{{ins.model}}</td>
                            <td>{{ins.year}}</td>
                            <td>{{ins.colour}}</td>
                            <td>{{ins.get_status_display}}</td>
                            <td>{{ins.scheduledDate|date:"M d, Y" }}</td>
                            <td>{{ins.id}}</td>
                        </tr>
                    {% endfor%}
                </table>
            </div>
        </div>
    </div>
    <br>
    <br>
</body>

{% endblock %}

background/templates/background/customers.html
{% extends 'background/base.html' %}

{% block title %}Customer Info{% endblock %}

{% block content %}

<body>
    <h2>{{header}}</h2>
    <br>

    <div class="row">
        <div class="col-md">
            <div class="card card-body">
                <table id="{{table_css_id}}" class="table">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Phone</th>
                            <th>City</th>
                            <th>Province</th>
                            <th>Inspection Count</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for cust in customers %}
                        <tr>
                            <td><a href="{% url 'customerinfo' cust.id %}">{{cust.first_name}} {{cust.last_name}}</a></td>
                            <td>{{cust.email}}</td>
                            <td>{{cust.phone}}</td>
                            <td>{{cust.city}}</td>
                            <td>{{cust.province}}</td>
                            <td>{{cust.inspection_count}}</td>

                        </tr>
                        {% endfor%}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</body>

{% endblock %}

{% block js %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.js"></script>
<script>
    $(document).ready(function () {
        $('#table_db').DataTable();
    });
</script>
</div>
{% endblock %}

background/templates/background/home.html
{% extends 'background/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}

<body>
    <h2>Physical Products</h2>
    <p>Are you a warranty customer? Please <a href="{% url 'login' %}">login</a> to view your account</p>
    <div class="row">
        {% for prod in products%}
            <div class="col-sm-4">
                <div class="card mb-3">
                    <img src="{{ prod.image.url }}" class="img-fluid card-img-top" alt="{{prod.name}}" style="max-height: 15vw; object-fit: cover;" >
                    <div class="card-body">
                    <h5 class="card-title">{{prod.name}}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">{{prod.category}}</h6>
                    <p class="card-text">{{prod.description}}</p>
                    <p>Only ${{prod.price}}!</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</body>

{% endblock %}

background/templates/background/message.html
<!-- Toasts Styling -->
<style>
  .notification {
    position: absolute;
    bottom: 2rem;
    right: 1rem;
  }
</style>

{% for message in messages %}
  <div class="toast notification bg-{% if message.tags == 'error' %}danger{% else %}{{message.tags}}{% endif %}" role="alert" aria-live="assertive" aria-atomic="true" data-delay="5000">
    <div class="toast-header">
      <strong class="me-auto">
        {% if message.tags == 'error' %}
          <i>Error!</i>
        {% elif message.tags == 'warning' %}
          <i>Warning!</i>
        {% elif message.tags == 'info' %}
          <i>Info.</i>
        {% elif message.tags == 'success' %}
          <i>Success!</i>
        {% endif %}
        <!-- {{message.tags|capfirst}} -->
      </strong>
    </div>
    <div class="toast-body">
      {{message|safe}}
    </div>
  </div>
{% endfor %}

background/templates/background/register.html
{% extends "background/base.html" %}

{% block title %}Create an Account{% endblock %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="POST" class="form-group">
	    {% csrf_token %}
	    {{ form|crispy }}
	<button type="submit" class="btn btn-success">Register</button>
    </form>
{% endblock %}